Document: phpreport
Title: Debian phpreport Manual
Author: <insert document author here>
Abstract: This manual describes what phpreport is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/phpreport/phpreport.sgml.gz

Format: postscript
Files: /usr/share/doc/phpreport/phpreport.ps.gz

Format: text
Files: /usr/share/doc/phpreport/phpreport.text.gz

Format: HTML
Index: /usr/share/doc/phpreport/html/index.html
Files: /usr/share/doc/phpreport/html/*.html

  
