--
-- PostgreSQL database dump
--

SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

SET search_path = public, pg_catalog;

--
-- Data for Name: consult; Type: TABLE DATA; Schema: public; Owner: -
--

COPY consult (id, title, sql, parameters, description, public) FROM stdin;
1	Rec. Horas de un trabajador por tipo y fecha (no comp)	SELECT uid, type, SUM(_end-init)/60.0 as sum_hours\r\nFROM task\r\nWHERE uid LIKE uid_trabajador AND \r\n   type LIKE type_name AND \r\n   _date>=fecha_inicio AND\r\n   _date<=fecha_fin\r\nGROUP BY uid, type	uid_trabajador,fecha_inicio,fecha_fin,type_name	Calcula el número de horas trabajadas por un trabajador en el intervalo desde "fecha_inicio" a "fecha_fin" (formato AAAA-MM-DD) para un tipo de tarea concreto.\r\nSe admite % como comodín en todos los campos de texto.	t
29	Recuento de horas de un trabajador por tipo, proyecto, fecha y texto	SELECT uid, type, name, text, SUM(_end-init)/60.0 - COALESCE((\r\n  SELECT SUM(hours)\r\n  FROM compensation\r\n  WHERE uid=task.uid\r\n   AND init>=fecha_inicio\r\n   AND _end<=fecha_fin\r\n ),0) AS suma_horas\r\nFROM task\r\nWHERE uid LIKE uid_trabajador AND \r\n   name LIKE project_name AND \r\n   type LIKE type_name AND \r\n   text LIKE task_text AND \r\n   _date>=fecha_inicio AND\r\n   _date<=fecha_fin\r\nGROUP BY uid, name, type, text	uid_trabajador,fecha_inicio,fecha_fin,type_name,project_name,task_text	Calcula el número de horas trabajadas por un trabajador en el intervalo desde "fecha_inicio" a "fecha_fin" (formato AAAA-MM-DD) para un trabajador concreto, para un tipo de tarea concreto y para un proyecto concreto y con un texto en concreto (se agrupan las tareas con el mismo texto)\r\nSe admite % como comodín en todos los campos de texto.	t
37	Recuento de horas por story, ttipo, tipo, proyecto, fecha (NULL incluido)	SELECT uid, type, name, phase, ttype, story, SUM(_end-init)/60.0 AS suma_horas\r\nFROM task\r\nWHERE uid LIKE uid_trabajador AND \r\n   name LIKE project_name AND \r\n   (story  LIKE story_name OR story is NULL) AND\r\n   (type LIKE type_name OR type is NULL) AND \r\n   (ttype LIKE tt_name OR ttype is NULL) AND \r\n   _date>=fecha_inicio AND\r\n   _date<=fecha_fin\r\nGROUP BY uid, name, phase, type, ttype, story	uid_trabajador,fecha_inicio,fecha_fin,story_name,type_name,tt_name,project_name	Calcula el número de horas trabajadas por un trabajador en el intervalo desde "fecha_inicio" a "fecha_fin" (formato AAAA-MM-DD) para un trabajador concreto, para un ttipo, tipo y story de tarea concreto y para un proyecto concreto.\r\nSe admite % como comodín en todos los campos de texto. No se tienen en cuenta las compensaciones. Muy útil para desagregar las horas de un proyecto por casos de uso.	t
15	Listado de compensaciones	SELECT * FROM compensation		Muestra un listado de todas las compensaciones existentes. <br>La compensación es un mecanismo que permite cambiar horas trabajadas por dinero, vacaciones, etc, de modo que dichas horas de más no se tengan luego en cuenta a la hora de generar los recuentos de horas totales trabajadas. Al estar compensadas (remuneradas) esas horas, será como si nunca hubiesen existido.	f
30	Recuento de horas de un trabajador por tipo y proyecto	SELECT uid, type, name, SUM(_end-init)/60.0  AS suma_horas\r\nFROM task\r\nWHERE uid LIKE uid_trabajador AND \r\n   name LIKE project_name AND \r\n   type LIKE type_name \r\nGROUP BY uid, name, type	uid_trabajador,type_name,project_name	Recuento de todas las horas de un trabajador (uid_trabajador) en un tipo  y en proyecto concreto (nombre)\r\n	t
44	Recuento de horas por ttipo, tipo, proyecto, fecha (NULL incluido)	SELECT uid, type, name, phase, ttype, SUM(_end-init)/60.0 AS suma_horas\r\nFROM task\r\nWHERE uid LIKE uid_trabajador AND \r\n   name LIKE project_name AND \r\n   (type LIKE type_name OR type is NULL) AND \r\n   (ttype LIKE tt_name OR ttype is NULL) AND \r\n   _date>=fecha_inicio AND\r\n   _date<=fecha_fin\r\nGROUP BY uid, name, phase, type, ttype	uid_trabajador,fecha_inicio,fecha_fin,type_name,tt_name,project_name	Calcula el número de horas trabajadas por un trabajador en el intervalo desde "fecha_inicio" a "fecha_fin" (formato AAAA-MM-DD) para un trabajador concreto, para un ttipo y tipo de tarea concreto y para un proyecto concreto.\r\nSe admite % como comodín en todos los campos de texto. No se tienen en cuenta las compensaciones.	t
12	Recuento general de horas trabajadas en un intervalo	SELECT uid, SUM(_end-init)/60.0 - COALESCE((\r\n  SELECT SUM(hours)\r\n  FROM compensation\r\n  WHERE uid=task.uid\r\n   AND init>=fecha_inicio\r\n   AND _end<=fecha_fin\r\n ),0) AS suma_horas\r\nFROM task\r\nWHERE _date>=fecha_inicio\r\n AND _date<=fecha_fin\r\nGROUP BY uid	fecha_inicio,fecha_fin	Calcula el número de horas trabajadas por todos los trabajadores en el intervalo desde "fecha_inicio" a "fecha_fin" (formato AAAA-MM-DD). A este número de horas se le descuentan automáticamente las horas ya compensadas por el trabajador en ese intervalo.	t
34	Recuento de horas de un trabajador por story, tipo, proyecto y fecha	SELECT uid, type, name, story, SUM(_end-init)/60.0 - COALESCE((\r\n  SELECT SUM(hours)\r\n  FROM compensation\r\n  WHERE uid=task.uid\r\n   AND init>=fecha_inicio\r\n   AND _end<=fecha_fin\r\n ),0) AS suma_horas\r\nFROM task\r\nWHERE uid LIKE uid_trabajador AND \r\n   name LIKE project_name AND \r\n   story  LIKE story_name AND\r\n   type LIKE type_name AND \r\n   _date>=fecha_inicio AND\r\n   _date<=fecha_fin\r\nGROUP BY uid, name, type, story	uid_trabajador,fecha_inicio,fecha_fin,story_name,type_name,project_name	Calcula el número de horas trabajadas por un trabajador en el intervalo desde "fecha_inicio" a "fecha_fin" (formato AAAA-MM-DD) para un trabajador concreto, para un tipo y story de tarea concreto y para un proyecto concreto.\r\nSe admite % como comodín en todos los campos de texto.	t
32	Recuento de horas de un proyecto	SELECT name, SUM(_end-init)/60.0 as hours\r\nFROM task\r\nWHERE \r\n   name LIKE project_name\r\nGROUP BY name\r\n	project_name	Recuento de todas las horas de un proyecto concreto (nombre)\r\n	t
35	Recuento de horas de un trabajador por tipo, ttipo, proyecto y fecha	SELECT uid, type, name, ttype,  SUM(_end-init)/60.0 - COALESCE((\r\n  SELECT SUM(hours)\r\n  FROM compensation\r\n  WHERE uid=task.uid\r\n   AND init>=fecha_inicio\r\n   AND _end<=fecha_fin\r\n ),0) AS suma_horas\r\nFROM task\r\nWHERE uid LIKE uid_trabajador AND \r\n   name LIKE project_name AND \r\n   type LIKE type_name AND \r\n   ttype LIKE ttipo_name AND\r\n   _date>=fecha_inicio AND\r\n   _date<=fecha_fin\r\nGROUP BY uid, name, type, ttype	uid_trabajador,fecha_inicio,fecha_fin,type_name,ttipo_name,project_name	Calcula el número de horas trabajadas por un trabajador en el intervalo desde "fecha_inicio" a "fecha_fin" (formato AAAA-MM-DD) para un trabajador concreto, para un tipo y ttipo de tarea concreto y para un proyecto concreto.\r\nSe admite % como comodín en todos los campos de texto.	t
31	Recuento general de horas trabajadas en la semana actual	SELECT uid, SUM(_end-init)/60.0 - COALESCE((\r\n  SELECT SUM(hours)\r\n  FROM compensation\r\n  WHERE uid=task.uid\r\n   AND init>=(current_timestamp - ((int2(date_part('dow',current_timestamp )+7-1) % 7)||' days')::interval)::date\r\n   AND _end<=(current_timestamp - ((int2(date_part('dow',current_timestamp)+7-1) % 7)-6||' days')::interval)::date\r\n ),0) AS suma_horas\r\nFROM task\r\nWHERE _date>=(current_timestamp - ((int2(date_part('dow',current_timestamp )+7-1) % 7)||' days')::interval)::date\r\n AND _date<= (current_timestamp - ((int2(date_part('dow',current_timestamp )+7-1) % 7)-6||' days')::interval)::date\r\nGROUP BY uid		Calcula el número de horas trabajadas por todos los trabajadores en la semana actual. A este número de horas se le descuentan automáticamente las horas ya compensadas por el trabajador en ese intervalo.	t
13	Borrado de informes y tareas de un trabajador en un intervalo	BEGIN TRANSACTION;\r\nDELETE FROM task WHERE uid=uid_trabajador AND _date>=fecha_inicio AND _date<=fecha_fin AND confirmacion='ok';\r\nDELETE FROM report WHERE uid=uid_trabajador AND _date>=fecha_inicio AND _date<=fecha_fin AND confirmacion='ok';\r\nCOMMIT TRANSACTION	uid_trabajador,fecha_inicio,fecha_fin,confirmacion	Borra todos los informes y tareas del trabajador uid_trabajador en el intervalo desde fecha_inicio hasta fecha_fin (formato AAAA-MM-DD).\r\nEs necesario introducir la palabra "ok" en confirmacion. Esto se hace para evitar borrar informes por error.	f
19	Tareas de un trabajador por proyecto en un intervalo 	SELECT uid,_date,\r\n to_char(init/60,'FM00')||':'||to_char(init%60,'FM00') as init,\r\n to_char(_end/60,'FM00')||':'||to_char(_end%60,'FM00') as _end,\r\n name,type,phase,ttype,story,text\r\nFROM task WHERE uid LIKE uid_trabajador AND name LIKE project_name AND _date>=fecha_inicio AND _date<=fecha_fin ORDER BY uid,_date,init	uid_trabajador, project_name,fecha_inicio,fecha_fin	Selección de todas las tareas de un trabajador (uid_trabajador) durante un determinado intervalo (fecha_inicio, fecha_fin).\r\nLas fechas deben estar en formato YYYY-MM-DD.Se admiten comodines (%) en el nombre del trabajador y el proyecto.	t
14	Añadir compensación	INSERT INTO compensation (uid,init,_end,hours,paid) VALUES (uid_trabajador,fecha_inicio,fecha_fin,num_horas,cantidad_pagada)	uid_trabajador,num_horas,fecha_inicio,fecha_fin,cantidad_pagada	Inserta una nueva compensación en la BD en la que al trabajador uid_trabajador se le conmuta una cierta cantidad de num_horas de horas extra durante el período desde fecha_inicio hasta fecha_fin a cambio de una cantidad_pagada de dinero. Las fechas están en formato AAAA-MM-DD.<br>La compensación es un mecanismo que permite cambiar horas trabajadas por dinero, vacaciones, etc, de modo que dichas horas de más no se tengan luego en cuenta a la hora de generar los recuentos de horas totales trabajadas. Al estar compensadas (remuneradas) esas horas, será como si nunca hubiesen existido.	f
16	Borrar compensación	DELETE FROM compensation WHERE uid=uid_trabajador AND init=fecha_inicio AND _end=fecha_fin	uid_trabajador,fecha_inicio,fecha_fin	Borra de la BD una compensación referente al trabajador uid_trabajador durante el intervalo desde fecha_inicio hasta fecha_fin. Las fechas están en formato AAAA-MM-DD. El intervalo debe coincidir exactamente con el de una compensación ya existente para que el borrado sea efectivo.<br>La compensación es un mecanismo que permite cambiar horas trabajadas por dinero, vacaciones, etc, de modo que dichas horas de más no se tengan luego en cuenta a la hora de generar los recuentos de horas totales trabajadas. Al estar compensadas (remuneradas) esas horas, será como si nunca hubiesen existido.	f
26	Borrar informes de todos los trabajadores en un intervalo	BEGIN TRANSACTION;\r\nDELETE FROM task WHERE _date>=fecha_inicio AND _date<=fecha_fin AND confirmacion='ok';\r\nDELETE FROM report WHERE _date>=fecha_inicio AND _date<=fecha_fin AND confirmacion='ok';\r\nCOMMIT TRANSACTION	fecha_inicio,fecha_fin,confirmacion		f
18	Borrar informes huérfanos	DELETE FROM report WHERE (SELECT COUNT(*) FROM task WHERE task.uid=report.uid AND task._date=report._date)=0		Borra informes que no tienen tareas asociadas	f
43	Listado de tareas de un trabajador por tipo, proyecto y fecha	SELECT uid, _date, name, type, text\r\nFROM task\r\nWHERE uid LIKE uid_trabajador AND \r\n   name LIKE project_name AND \r\n   type LIKE type_name AND \r\n   _date>=fecha_inicio AND\r\n   _date<=fecha_fin\r\nGROUP BY uid, _date, name, type, text\r\nORDER BY _date	uid_trabajador,fecha_inicio,fecha_fin,type_name,project_name	Lista las tareas realizadas por un trabajador en el intervalo desde "fecha_inicio" a "fecha_fin" (formato AAAA-MM-DD) para un trabajador concreto, para un tipo de tarea concreto y para un proyecto concreto.\r\nSe admite % como comodín en todos los campos de texto.	t
42	Horas totales vs. horas anuales	select tblTotal.nombre, horasTotal,horasAnho\r\nfrom\r\n (select sum(_end-init)/60.0 as horasTotal, name\r\n from task\r\n where name like nombre_proyecto\r\n group by name\r\n ) as tblTotal,\r\n (select sum(_end-init)/60.0 as horasAnho,name\r\n from task\r\n where name like nombre_proyecto\r\n  and _date>=fecha_inicio and _date<=fecha_fin\r\n group by name\r\n ) as tblAnho\r\nwhere tblTotal.nombre=tblAnho.nombre\r\n	nombre_proyecto, fecha_inicio, fecha_fin	Indica cuántas horas se han realizado de un proyecto en una fecha concreta en contraposición con las que se han realizado en toda la historia del proyecto. Sólo tiene en cuenta aquellos proyectos que tengan tareas dentro de esos límites temporales.	f
11	Listado de bloqueos	SELECT * FROM block		Esta consulta muestra el listado de bloqueos para todos los empleados.	f
10	Listado de consultas	SELECT * FROM consult ORDER BY id		Esta consulta muestra el listado de todas las consultas definidas.	f
23	Listado de informes huérfanos	SELECT * FROM report WHERE (SELECT COUNT(*) FROM task WHERE task.uid=report.uid AND task._date=report._date)=0		Lista aquellos informes que no tienen ninguna tarea dentro	f
2	Listado de tareas	SELECT * FROM task ORDER BY uid,init		Esta consulta selecciona todas las tareas ordenadas por usuario y fecha.	f
46	Duración en días y horas de historias de un proyecto (no comp)	SELECT min(_date) as fecha_inicio,\r\n       max(_date) as fecha_fin,\r\n       (max(_date)-min(_date)+1) as duracion_dias,\r\n       trim(story) as nombre_story,\r\n       SUM(_end-init)/60.0  AS suma_horas\r\nFROM task\r\nWHERE\r\n   name LIKE project_name AND\r\n   (story LIKE story_name OR story IS NULL)\r\nGROUP BY name, story\r\nORDER BY fecha_inicio\r\n	project_name,story_name	Recuento de días y horas de las stories de un proyecto.\r\nSe admite % como comodín en todos los campos de texto.	t
45	Recuento de horas por fecha y proyecto	SELECT name, SUM(_end-init)/60.0 - COALESCE((\r\n  SELECT SUM(hours)\r\n  FROM compensation\r\n  WHERE init>=fecha_inicio\r\n   AND _end<=fecha_fin\r\n ),0) AS suma_horas\r\nFROM task\r\nWHERE name LIKE project_name AND \r\n   _date>=fecha_inicio AND\r\n   _date<=fecha_fin\r\nGROUP BY name	fecha_inicio,fecha_fin,project_name	Recuento de todas las horas entre dos fechas y en proyecto concreto (nombre)	t
41	Rec. Horas de un trabajador por tipo, proyecto y fecha (no comp)	SELECT uid, type, name, SUM(_end-init)/60.0 as sum_hours\r\nFROM task\r\nWHERE uid LIKE uid_trabajador AND \r\n   name LIKE project_name AND \r\n   type LIKE type_name AND \r\n   _date>=fecha_inicio AND\r\n   _date<=fecha_fin\r\nGROUP BY uid, name, type	uid_trabajador,fecha_inicio,fecha_fin,type_name,project_name	Calcula el número de horas trabajadas por un trabajador en el intervalo desde "fecha_inicio" a "fecha_fin" (formato AAAA-MM-DD) para un trabajador concreto, para un tipo de tarea concreto y para un proyecto concreto.\r\nSe admite % como comodín en todos los campos de texto.	t
\.
